# Generated by Django 4.2 on 2023-04-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=128, verbose_name='Аэропорт вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city_code',
            field=models.CharField(max_length=10, verbose_name='Код аэропорта прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_location',
            field=models.CharField(max_length=128, verbose_name='Город прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_terminal',
            field=models.CharField(max_length=10, verbose_name='Терминал аэропорта прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='class_type',
            field=models.CharField(max_length=20, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(max_length=128, verbose_name='Аэропорт вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city_code',
            field=models.CharField(max_length=10, verbose_name='Код аэропорта вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location',
            field=models.CharField(max_length=128, verbose_name='Город вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_terminal',
            field=models.CharField(max_length=10, verbose_name='Терминал аэропорта вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight',
            field=models.CharField(max_length=128, verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='luggage',
            field=models.CharField(max_length=10, verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flights', to='ticket.ticket', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='document_number',
            field=models.CharField(max_length=9, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(max_length=6, verbose_name='Номер PNR'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rl_number',
            field=models.CharField(max_length=6, verbose_name='Номер RL'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=14, verbose_name='Номер билета'),
        ),
    ]
