# Generated by Django 4.2 on 2023-04-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_flight_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Информация о маршруте', 'verbose_name_plural': 'Информация о маршрутах'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Информация о пассажире', 'verbose_name_plural': 'Информация о пассажирах'},
        ),
    ]
