# Generated by Django 4.2 on 2023-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_flight_options_alter_ticket_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_city_code',
            new_name='arrival_airport_code',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure_city_code',
            new_name='departure_airport_code',
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(max_length=128, verbose_name='Город прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_location',
            field=models.CharField(max_length=128, verbose_name='Аэропорт прилёта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(max_length=128, verbose_name='Город вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location',
            field=models.CharField(max_length=128, verbose_name='Аэропорт вылета'),
        ),
    ]
