# Generated by Django 4.2 on 2023-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rename_flight_flight_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='document_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Номер PNR'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rl_number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Номер RL'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=14, unique=True, verbose_name='Номер билета'),
        ),
    ]
